#!/bin/sh -e
#
# Configure and launch the docker container
#

not_configured() {
  echo Conjur web service container not configured.
  echo
  echo You need to create /etc/conjur.container and put your app launch script in /etc/scripts/launch.
  echo See /etc/conjur.container.example for reference.
  if [ -t 1 ]; then
    sh
  fi
  exit 1
}

/opt/conjur/configure || not_configured

echo Starting nginx...
mkdir -p /tmp/nginx
nginx

echo Starting application...
/etc/scripts/launch
