#!/bin/sh -e
#
# Configure and launch the docker container
#

if ! [ -z "$DEBUG" ]; then
  set -x
fi

if ! [ -e /etc/conjur.conf ]; then
  /etc/scripts/configure
  echo Container configured.
fi

export ASGARD_HOME=/var/lib/asgard
mkdir -p $ASGARD_HOME

CNF=`conjur env template -c /etc/asgard/asgard.env.yaml /etc/asgard/asgard.conf.erb`
# NOTE: this will wipe out any existing Asgard config.
ln -sf $CNF $ASGARD_HOME/Config.groovy
echo Asgard configuration loaded from Conjur.

echo Launching nginx...
mkdir -p /tmp/nginx
nginx

CMD="java -Xmx1024M -XX:MaxPermSize=128m -jar /opt/asgard/asgard-standalone.jar"

if [ -t 1 ]; then
  echo
  echo TTY detected. Dropping to shell for development instead of launching.
  echo Would execute: $CMD
  echo
  sh
else
  echo Launching asgard...
  $CMD
fi
